export default function Home() {  
  return (
    
    <main className="flex min-h-screen flex-col ">
      <h1>hey, im julio 👋</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam commodi odit beatae eligendi necessitatibus optio numquam molestias aspernatur libero, illum vel impedit placeat facere dolores fugiat tempore possimus molestiae dolorum?
      Nam voluptatum quidem ex quibusdam corrupti maiores at? Magni, aperiam. Rem odit, accusantium ratione commodi similique id blanditiis vel natus amet in non vero error. Inventore eligendi ex incidunt ullam!
      Adipisci voluptas, quasi quaerat minima error, delectus natus rem voluptatem quam ducimus vel atque reiciendis ut? Quasi, expedita explicabo quos sapiente voluptatum unde obcaecati deleniti debitis sint ipsam, ipsum assumenda.
      Quaerat cum voluptatem veritatis numquam maiores sequi natus non temporibus officia placeat ut in ad dicta magnam facilis, recusandae sint necessitatibus excepturi optio! Minus sed sequi possimus cupiditate iste ab.
      Illum necessitatibus, totam unde voluptas repellat voluptates quibusdam soluta id labore vero et mollitia reiciendis explicabo, laborum sit, repellendus qui corporis. Voluptates repellat quos amet? Quos nobis corporis pariatur perferendis!
      Assumenda eum maxime architecto deleniti, quibusdam, rem aliquid quas et incidunt cumque a, repudiandae temporibus accusantium tempora dignissimos atque fuga doloremque nisi omnis. Qui, deleniti amet esse laboriosam numquam totam.
      Error veniam, quas ut aspernatur voluptate earum, et alias architecto nam ipsa repudiandae facilis placeat excepturi, laboriosam nobis asperiores. Molestiae unde velit ratione odio corrupti dolorum, sed quaerat? Cumque, deleniti.
      Consequatur, nulla error, fuga quae nemo iusto quas tenetur deserunt, dolorem in quod rerum doloremque pariatur accusantium eveniet itaque fugiat tempora sit ad quo nam accusamus quidem voluptas nostrum? Amet.
      Ad eum recusandae sapiente enim autem totam vitae nulla natus laboriosam, ipsam, excepturi ut iusto obcaecati porro deleniti facilis officia dolorum cumque ex? Architecto excepturi nostrum est perferendis numquam officia.
      Minus mollitia adipisci dicta, laborum ipsa repellendus hic temporibus fugit enim. Voluptatem maxime voluptatum repellendus quod mollitia, maiores odio cum sed natus, illum rem. Amet quod sunt tempora sed aspernatur.
      Cupiditate sequi doloribus veniam sunt eligendi minima in amet inventore iste quaerat nam, ut quidem, earum, eaque ipsam. Repellendus neque esse labore corporis error reiciendis, expedita a sit praesentium repellat.
      Sequi, doloribus! Minima laboriosam neque placeat modi harum adipisci quae repellat repellendus eos et officia quo recusandae vero impedit, dolores ullam sit numquam accusantium exercitationem consequatur itaque, perferendis, molestiae molestias.
      Iusto cum praesentium consectetur nobis ipsum! Laboriosam tempore earum nulla. Accusantium, ipsa, minima suscipit esse quod at eveniet officiis, ullam maiores quae autem eligendi obcaecati maxime delectus natus repellendus numquam!
      Pariatur dignissimos temporibus animi amet rerum? Sequi quibusdam excepturi quos, tempora illum doloremque eaque perferendis impedit voluptatibus incidunt nostrum facilis iste earum voluptates est consequatur hic repellat vitae molestiae pariatur.
      Delectus excepturi maxime inventore, quod voluptatum error illum quae, labore praesentium iure esse eos, minima totam incidunt sunt facilis? Minus sit facilis quisquam molestiae fugit voluptatibus id, ea incidunt impedit?
      Esse qui laboriosam incidunt explicabo, quae quod! Quas minima quod provident autem magni fugit explicabo mollitia modi. Tempora, similique. Suscipit qui numquam ut veritatis, voluptas corrupti eos asperiores cumque tenetur!
      Facilis non provident excepturi sapiente voluptates harum assumenda incidunt sed error. Cumque aliquam deserunt placeat dolores minima nihil, saepe qui quae voluptate explicabo, porro ut repudiandae et corporis perspiciatis totam.
      Perspiciatis velit earum praesentium a obcaecati impedit, deleniti dolorem exercitationem maiores illum rem, facere ad! Veniam maiores aut consequatur, saepe neque assumenda hic facilis tenetur quidem. Ipsam magnam vel consequuntur?
      Corrupti distinctio rem perspiciatis aliquam quasi officia! Sunt eius eos est illum, error a quasi ea consequatur placeat optio fugiat molestias nemo aliquid sequi exercitationem, voluptatem facere? Soluta, rerum dolor.
      Cumque esse eius optio, recusandae incidunt autem ex, quod facere nemo aspernatur quisquam eveniet error deleniti eos, nam consequatur tempore consequuntur. Sint temporibus repellendus aliquam aperiam inventore sapiente amet enim.
      Atque dolorem, aspernatur odio itaque est a provident voluptatem perspiciatis ad debitis aliquam ut sunt qui animi nam earum suscipit iure neque quibusdam hic obcaecati iste corporis ratione! Eius, saepe.
      Quibusdam harum sit perspiciatis est. Cupiditate earum maxime eligendi ea similique dolorum atque modi, aut eaque beatae quo, distinctio mollitia vel harum deleniti nihil iste? Recusandae eius nobis officiis nihil?
      Incidunt, soluta rerum? Sit quisquam consequatur perspiciatis cumque sint voluptate dolorem delectus numquam veritatis earum. Asperiores harum voluptatum ipsa minima, neque itaque error perferendis cum molestiae beatae reiciendis! Mollitia, autem.
      Perspiciatis quas, modi cupiditate consequuntur iste quisquam? Libero officiis eaque aperiam ea fugiat qui. Esse, iste laudantium pariatur veritatis, architecto vero, impedit molestias beatae ipsa facere illo provident consectetur? Laudantium?
      Voluptates dolore deleniti quos in libero alias repudiandae odio distinctio molestias? Tenetur corporis, earum mollitia asperiores aspernatur cupiditate architecto pariatur assumenda eius sint excepturi veritatis ipsum dolores laudantium sapiente perspiciatis.
      Libero, suscipit. Sunt neque autem veniam cumque ut, porro expedita illo eveniet! Nobis accusamus quisquam voluptatibus cupiditate, veniam molestias fugit repellat deserunt. Distinctio nostrum temporibus necessitatibus error voluptatum assumenda cum!
      Perferendis, accusamus repellendus maxime odio asperiores ex blanditiis dignissimos sequi cum explicabo ipsam consectetur labore magni ipsum vitae error praesentium? Voluptates quaerat fugiat voluptate quasi laborum, praesentium porro. Officia, adipisci.
      Quia, voluptatem consectetur laboriosam quae, earum libero officia, itaque odit impedit animi exercitationem cupiditate numquam repudiandae nihil culpa tenetur vel! Iste nulla vero animi quis dolorum aspernatur sequi iure maxime.
      Consequuntur sed ipsam incidunt libero nihil eligendi dignissimos ut. Consequuntur iure earum quaerat optio, quae maiores delectus est impedit nostrum at sunt quam dolorem odit voluptates consequatur ea ipsum enim?
      Facere deleniti quasi aperiam minus ipsam perferendis similique architecto at accusantium quod repudiandae provident eius corrupti hic mollitia eaque doloribus obcaecati nulla, amet consequatur maxime ab laborum optio sunt? Expedita.
      Modi provident accusantium rerum, delectus illo, vitae veritatis autem perspiciatis in, quis labore nulla repellendus nisi sequi ex. Quas debitis accusantium perspiciatis delectus harum ad quis, in quaerat. Accusantium, corrupti!
      Nemo quod eius quia assumenda labore aperiam, corporis eligendi unde dolorum odit. Odit soluta optio magnam ad ipsum vero impedit, atque eum illum natus possimus veniam vel dolorum ut deserunt.
      Soluta saepe, inventore voluptas vitae fuga cum non asperiores dolor impedit corrupti. Magni harum repellat assumenda consequuntur. Consequatur cum veniam, quam deserunt illo iusto eaque aliquid maiores. Minima, non? Nulla?
      Quam optio similique possimus aliquid hic, esse laudantium et tempore ad id dignissimos voluptates corrupti nulla? Tempore, quibusdam ut? Provident nostrum voluptatem dolore, magni ut id alias magnam at amet.
      Inventore, placeat quae ad, consectetur consequuntur incidunt iusto sunt explicabo sit ratione nostrum ut maxime, at dolor exercitationem libero totam? Corporis nobis magni dignissimos accusamus omnis explicabo, quam esse non!
      Eligendi et architecto ex aut? Suscipit vel hic quaerat, tempore quam consequuntur harum cumque provident! Quia dolore, et dignissimos consequuntur, eum possimus aperiam explicabo quae deserunt nisi repudiandae cupiditate vero.
      Dolorum iste itaque non nihil soluta doloremque culpa quod repellat, mollitia eligendi aperiam eius quasi vel inventore vitae earum consequuntur officiis minima. Quis perferendis asperiores itaque! Ullam officiis autem cum!
      Expedita corrupti aut, sapiente delectus ullam dolore voluptatem quia numquam necessitatibus reiciendis voluptate at odit, temporibus neque. Quod, ipsam iste, consequatur corrupti saepe, ipsum reprehenderit maxime officiis voluptas cupiditate magnam.
      Pariatur ea dolor officia nobis, quia culpa. Deleniti dignissimos, maiores quisquam totam ducimus perferendis necessitatibus iusto quibusdam exercitationem accusamus mollitia, voluptate, enim quia assumenda. Magni exercitationem non dolores itaque iste.
      Error a laborum fugiat cupiditate corporis hic officiis soluta quam culpa? Ad, nemo voluptatem quo neque error ullam illum sunt sapiente magni nihil hic veniam, ea eius quasi inventore sequi.
      Nam explicabo totam quis impedit alias incidunt, perferendis fugiat ducimus recusandae? Veritatis possimus, assumenda ex molestiae dignissimos debitis officia animi magni suscipit doloremque nulla illum provident eligendi maxime dolorum repellendus.
      Laborum iste odio error voluptatem, rem enim officia, unde magni quisquam corporis, veritatis earum. Aut repudiandae distinctio quia quis corporis qui eos tempora a illo labore, porro, rerum pariatur. Nulla.
      Facilis ullam quibusdam labore? Harum ipsum vero, quo exercitationem dicta magnam, veniam dolorem obcaecati dolor modi quos corrupti asperiores delectus nam impedit quaerat quidem alias quod eum architecto doloribus. Ratione!
      Repellat animi recusandae obcaecati explicabo numquam sunt. Dolores sapiente adipisci suscipit impedit neque consequatur quasi deleniti cupiditate, inventore repudiandae ipsa quisquam officiis praesentium numquam, a, tempora reprehenderit officia dignissimos ex.
      Dolor sapiente totam accusantium perferendis doloribus minima, eligendi delectus, corrupti accusamus ullam omnis iure tenetur quibusdam! Debitis ipsam nihil vel sequi modi tenetur, quibusdam, neque aliquid labore doloremque enim hic?
      Dolores, laborum repellendus maiores unde officia dolor. Accusantium voluptatibus possimus quasi repellendus quos tempore eos illo ullam vitae atque, nam voluptatem alias, nostrum obcaecati illum! Doloremque illum illo voluptates tempore?
      Nihil eveniet quae porro qui! Quas, fugit nam officia delectus accusantium fugiat impedit. Recusandae ducimus dolore eius doloribus deserunt, alias ipsam non omnis pariatur consequuntur animi sit blanditiis ullam ad.
      Doloremque sunt, quam repellat, nesciunt temporibus, corrupti officia aliquid dolorem tempore corporis enim voluptatem error omnis placeat soluta ratione earum sint obcaecati vitae aliquam doloribus iste. Illum labore aliquam fugit.
      Praesentium quod laborum dicta similique cumque, ipsa exercitationem. Cumque laborum nostrum voluptatum, odit illum dignissimos sed hic eaque, architecto, eum amet odio expedita reprehenderit facilis commodi cupiditate dolore officiis quam?
      Error cumque mollitia odio ipsum soluta accusantium corrupti culpa perferendis, dolor maxime, iusto minima voluptate est quae et dolore dignissimos explicabo ex molestias officia, odit facere eius laudantium! Enim, culpa.</p>
    </main>
  );
}
