name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - closed

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Azure Static Web Apps
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
        uses: Azure/static-web-apps-deploy@v1.1.7
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_MEADOW_0EF444E1E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Token para integrações do GitHub (ex: comentários em PRs)
          action: "upload"
          app_location: "/" # Caminho do código fonte do App
          api_location: "" # Caminho do código fonte da API (se houver)
          output_location: "" # Caminho de saída do app compilado

      - name: Close Pull Request Deployment
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        uses: Azure/static-web-apps-deploy@v1.1.7
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_MEADOW_0EF444E1E }}
          action: "close"
